"""
CATS — Shared Configuration
"""
import os

EXCHANGE_RATE_PER_POINT = 0.01  # $0.01 per point = $0.01 compute credit
QUARTERLY_ISSUANCE_CEILING_MULTIPLIER = 2.0
HELPFULNESS_MULTIPLIER_CEILING_DEFAULT = 2.0
HELPFULNESS_MULTIPLIER_CEILING_INFLATION = 1.5

DECAY_RATE_PER_QUARTER = 0.10
DECAY_FLOOR_CREDITS = 500
DECAY_ACTIVE_WINDOW_DAYS = 90

TRUST_REPUTATION_HIGH_THRESHOLD = 0.90
TRUST_REPUTATION_LOW_THRESHOLD = 0.60
TRUST_BONUS_HIGH = 0.10
TRUST_PENALTY_LOW = -0.20

VELOCITY_LIMIT_PER_DAY = 8
SIMILARITY_FLAG_THRESHOLD = 0.75
COLLUSION_MUTUAL_VALIDATION_LIMIT = 3
BOT_DETECTION_SECONDS = 90

STAKE_MAX_CREDITS = 500
STAKE_UPHOLD_BONUS = 50

GOVERNANCE_COMMUNITY_MAJORITY = 0.50
GOVERNANCE_EXPERT_THRESHOLD = 0.60
GOVERNANCE_VOTE_LOCKOUT_DAYS = 30
GOVERNANCE_ACTIVE_VOTER_DAYS = 90
GOVERNANCE_DISPUTE_DAYS = 7

TERMS_VERSION = "2024-Q2-v1"
